In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
import statsmodels.formula.api as smf
from sklearn.metrics import r2_score

In [3]:
data = pd.read_csv("../datasets/Advertising.csv", index_col=0)

In [4]:
feature_cols = ['TV', 'radio', 'newspaper']
x = data[feature_cols]
y = data.sales

In [5]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [6]:
print(reg.intercept_)
print(reg.coef_)

2.9388893694594085
[ 0.04576465  0.18853002 -0.00103749]


In [7]:
# create a fitted model with all three features
lm = smf.ols(formula='sales ~ TV + radio + newspaper', data=data).fit()

# print the coefficients
lm.params

Intercept    2.938889
TV           0.045765
radio        0.188530
newspaper   -0.001037
dtype: float64

In [8]:
print(reg.score(x, y))
print(r2_score(y, reg.predict(x)))

0.8972106381789521
0.8972106381789522


In [9]:
from sklearn import svm

In [24]:
leg = svm.SVR(kernel='linear')

In [ ]:
y_train = f(x_train) + np.random.randn(m)
x_train = np.array(x_train).reshape(-1, 1)
x_test = np.array(x_test).reshape(-1, 1)

In [17]:
filedata = '../datasets/SVM_Dataset1.csv'
data1 = pd.read_csv(filedata)
data1

Unnamed: 0        X1        X2  y
0           0  2.947814  6.626878  1
1           1  2.530388  7.785050  1
2           2  3.566991  5.651046  1
3           3  3.156983  5.467077  1
4           4  2.582346  4.457777 -1
5           5  2.155826  6.222343 -1
6           6  3.273418  3.520687 -1

In [18]:
X1=data1['X1']
X2=data1['X2']
X_training=np.array(list(zip(X1,X2)))
X_training

array([[2.947814, 6.626878],
       [2.530388, 7.78505 ],
       [3.566991, 5.651046],
       [3.156983, 5.467077],
       [2.582346, 4.457777],
       [2.155826, 6.222343],
       [3.273418, 3.520687]])

In [19]:
y_training=data1['y']
y_training

0    1
1    1
2    1
3    1
4   -1
5   -1
6   -1
Name: y, dtype: int64

In [20]:
target_names=['-1','+1']
target_names

['-1', '+1']

In [23]:
svc = svm.SVC(kernel='linear').fit(X_training,y_training)
svc
svc.support_vectors_

array([[2.155826, 6.222343],
       [3.273418, 3.520687],
       [3.566991, 5.651046],
       [3.156983, 5.467077]])

In [25]:
svc.n_support_

array([2, 2], dtype=int32)

In [26]:
svc.support_ 

array([5, 6, 2, 3], dtype=int32)